// swift-tools-version: 6.0
import PackageDescription

// Migration proof compiles the original model files in their historical Muses module.
// It is independent of the public iOS application's distribution allowlist.
let package = Package(name: "MusesLegacyProof", platforms: [.macOS(.v14), .iOS(.v18)],
    products: [.executable(name: "LegacyProcessHarness", targets: ["LegacyProcessHarness"])],
    dependencies: [.package(path: "Packages/MusesPersistence")],
    targets: [
        .target(name: "Muses", dependencies: ["MusesPersistence"], path: "Sources/Muses",
                exclude: [
                    "App/AppComposition.swift",
                    "App/AppleMusicTokens.swift",
                    "App/GlassSurface.swift",
                    "App/MusesApp.swift",
                    "App/MusesRuntime.swift",
                    "App/PublicStoreLocation.swift",
                    "App/PublicCredentialDeletion.swift",
                    "App/PublicWebsiteDataDeletion.swift",
                    "App/PublicYouTubeApp.swift",
                    "CarPlay",
                    "Domain/ArtistOnlineDiscography.swift",
                    "Domain/Discovery",
                    "Domain/LoadState.swift",
                    "Domain/Notifications.swift",
                    "Domain/PlayerState.swift",
                    "Domain/SpectrumFrame.swift",
                    "Domain/TrackSnapshot+PlaybackContext.swift",
                    "Features",
                    "Infrastructure",
                    "Persistence/MusesModelContainer.swift",
                    "Platform",
                    "Resources",
                    "Services",
                ],
                sources: [
                    "Domain/Track.swift",
                    "Domain/QueueState.swift",
                    "Domain/Playlist.swift",
                    "Domain/PlaylistItem.swift",
                    "Domain/YouTubeImport.swift",
                    "Domain/YouTubeImportItem.swift",
                    "Domain/NotesModels.swift",
                    "Domain/ListeningEvent.swift",
                    "Domain/ListeningSession.swift",
                    "Domain/InboxItem.swift",
                    "Domain/EQPreset.swift",
                    "Domain/AutomationRule.swift",
                    "Domain/FocusSession.swift",
                    "Domain/YouTubeCatalog.swift",
                    "Domain/YouTubePlaylistSync.swift",
                    "Domain/Enums.swift",
                    "Domain/QueueItem.swift",
                    "Domain/QueueGroup.swift",
                    "Domain/ListeningContext.swift",
                    "Domain/EQBand.swift",
                    "Domain/RecapRange.swift",
                    "Domain/Pagination.swift",
                    "Domain/UserPreferences.swift",
                    "App/L10n.swift",
                    "Persistence/MusesSchema.swift",
                    "Persistence/LegacyMigration",
                ]),
        .executableTarget(name: "LegacyProcessHarness", dependencies: ["Muses", "MusesPersistence"],
            path: "Tests/LegacyProcessHarness"),
        .testTarget(name: "LegacyMigrationTests", dependencies: ["Muses", "MusesPersistence"],
                    path: "Tests/LegacyMigrationTests", resources: [.copy("Fixtures")])
    ])
